const express = require("express")
const path = require("path")
const ejs = require("ejs")
const app = express()
const gigRoute = require("./gigs/gigRoute")
const userRoute = require("./user/userRoute")
const sequelize = require("./config/connection")
app.use(express.json())
app.use(express.static(path.join(__dirname, "public")))
app.set("view engine", "ejs")
app.use(gigRoute)
app.use(userRoute)
app.listen(3002, ()=> console.log("connected to port 3002"))